# Generated by Django 5.0.7 on 2024-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('AD', 'ادویه جات'), ('DM', 'دمنوش'), ('AR', 'عرقیجات'), ('RO', 'روغن'), ('SB', 'سبزیجات خشک')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
