# Generated by Django 5.0.6 on 2024-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AD', 'ادویه جات'), ('DM', 'دمنوش'), ('AR', 'عرقیجات'), ('RO', 'روغن'), ('SB', 'سبزیجات خشک')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
